name: CI

permissions:
  contents: read

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        node: [20.10]
        experimental: [false]
    name: ðŸ‘· CI Styliz with Node-${{ matrix.node }} under ${{ matrix.os }}

    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4

      - name: ðŸŽ‰ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: âœ¨ Install dependencies
        run: |
          corepack enable
          make install

      - name: âœ… Check code style
        run: make check

      - name: ðŸ§ª Test components
        run: make test
